version: '2'

services:
  mobx-steam-db:
    image: postgres:latest
    extends:
      file: ../docker-compose.env.yml
      service: mobx-steam.env

  mobx-steam-server:
    image: mobx-steam-server:latest
    extends:
      file: ../docker-compose.env.yml
      service: mobx-steam.env
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5000:5000"
    links:
        - mobx-steam-db
    volumes:
      - "./server:/usr/src/app/server"